language: java

install :
 - mvn install
 - mvn sonar:sonar -SONAR_PROJECT_KEY=HeyChef_Ecommerce -SONAR_ORGANIZATION=heychef-github -SONAR_HOST=https://sonarcloud.io -SONAR_LOGIN=0511c56f47cf52740215000a6418235e32503346
